REMOTE="gdrive"
REMOTE_DIR="Backups"

TEMP_DIR="$HOME/backup/temp"
LOG_DIR="$HOME/backup/logs"

KEEP_ARCHIVES=30

TRANSFERS=4
CHECKERS=8

SYNC_PATHS=(
)

ARCHIVE_PATHS=(
    # "$HOME/Documents/Univer"
)

COPY_PATHS=(
)

